- name: Zookeeper | create group
  group:
    name: zookeeper
    state: present
  tags: zookeeper

- name: Zookeeper | create user
  user:
    name: zookeeper
    group: zookeeper
  tags: zookeeper

- name: Zookeeper | Setting internal variable
  set_fact:
    zk_name: zookeeper-{{ zk.version }}
  tags: zookeeper

- name: Zookeeper | Setting internal variable
  set_fact:
    zk_dir: "{{ zk.install_dir }}/{{ zk_name }}"
  tags: zookeeper

- name: Zookeeper | check if tar has been downloaded
  command: test -f /tmp/zookeeper/{{ zk_name }}/{{ zk_name }}.tar.gz
  register: zookeeper_tar_downloaded
  failed_when: zookeeper_tar_downloaded.rc not in [0, 1]
  changed_when: False
  tags: zookeeper

- name: Zookeeper | Ensure Zookeeper tar is downloaded
  get_url:
    url: "{{ zk.mirror }}/zookeeper/{{ zk_name }}/{{ zk_name }}.tar.gz"
    dest: /tmp
  tags: zookeeper
  when: zookeeper_tar_downloaded.rc == 1

- name: ZooKeeper | Ensure tar is extracted
  command: tar xzf /tmp/{{ zk_name }}.tar.gz chdir="{{ zk.install_dir }}"
  tags: zookeeper

# Config and start Zookeeper
- name: ZooKeeper | Ensure zoo.conf is present
  template:
    src: zoo.cfg
    dest: "{{ zk_dir }}/conf/zoo.cfg"
  notify: restart zookeeper
  tags: zookeeper

- name: ZooKeeper | Ensures data dir {{zk.data_dir}} exists
  file:
    path: "{{ zk.data_dir }}"
    state: directory
  tags: zookeeper

- name: ZooKeeper | Ensure myid is set to {{ cluster_node_seq }} in {{ zk.data_dir }}/myid
  template:
    src: myid
    dest: "{{ zk.data_dir }}/myid"
  notify: restart zookeeper
  tags: zookeeper

- name: ZooKeeper | systemd start script
  template:
    src: zookeeper-systemd.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 644
  notify: start zookeeper
  tags: zookeeper
